blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/calendar-io/calendar-io/discussions
    about: If you can't get something to work, open a question in our discussion forums.
  - name: Feature Request
    url: https://github.com/calendar-io/calendar-io/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
